apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-trainee
rules:
- apiGroups: [""] # "" indicates the core API group (Deployment,Replicaset etcc.. which are with v1 service)
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
