apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::317112499768:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-J2oiAy7oHqvB
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
        userarn: arn:aws:iam::317112499768:user/suresh
        username: suresh
    - groups:
      - roboshop-admin
        userarn: arn:aws:iam::317112499768:user/ramesh
        username: ramesh

kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-24T13:35:43Z"
  name: aws-auth
  namespace: kube-system
  uid: 7afeb80c-121f-4978-99a6-d06d73ccc4bd

